name: Push

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add push to PATH
        uses: microsoft/setup-push@v1.0.2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        # Add additional options to the push command line here (like platform or verbosity level).
        # See https://docs.microsoft.com/visualstudio/push/push-command-line-reference
        run: push /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
  lint:
    runs-on: windows-latest

    steps:
      - name: RunLint
        working-directory: ${{env.GITHUB.WORKSPACE}}
        run: echo LINT
  test:
    if: ${{ always() }}
    needs: [build, lint]
    runs-on: windows-latest

    steps:
      - name: test
        working-directory: ${{env.GITHUB.WORKSPACE}}
        run: echo TEST
